# ICB Colours Vector
#
# The colours that are used in the ICB theme. Non-exported (used by
# other functions e.g. icb_theme_cols)
icb_theme_colours <- c(
    green = "#8cedab",
    light_blue = "#4fbff0",
    orange = "#fc8700",
    deep_navy = "#031d44",
    purple = "#b88ce3",

    nhs_blue = "#005EB8",
    light_slate = "#b2b7b9",
    charcoal = "#2c2825",
    white = "#ffffff",
    #light_charcoal = "#9d928a",
    #light_slate = "#b2b7b9",
    #light_blue = "#abc0e0",
    #light_red = "#f5b2aa",

    #dark_orange = "#7c5f03",
    #dark_charcoal = "#151412",
    #dark_slate = "#343739",
    #dark_blue = "#263f66",
    #dark_red = "#901d10"
    cluster_green1 = "#28A745",
    cluster_green2 = "#1FA766",
    cluster_turquoise = "#1AA6A0",
    cluster_lightblue = "#1A92C7",
    cluster_blue = "#2E6FCA",
    cluster_darkblue = "#4E54B0",
    cluster_purple = "#6C4993",
    cluster_purplepink = "#8C4475",
    cluster_pinkorgange = "#B8484E",
    cluster_orange = "#F16522"
)



#' ICB Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' ICB palettes
#'
#' @param palette The name of palette to use. 'cluster' is the BSOL / BC cluster colours and default.
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @return A colorRamp function
#' @export
#'
#' @examples
#' icb_theme_pal("cluster")
#' icb_theme_pal("bsol")
#' # or, specify a palette
#' icb_theme_pal("ics_orange")
#' # a reverse palette
#' icb_theme_pal("cluster", TRUE)
icb_theme_pal <- function(palette = c(
    "cluster",
    "bsol",
    "alternative",
    "ics_blue",
    "ics_orange",
    "ics_green",
    "ics_purple",
    "ics_navy"
),
reverse = FALSE,
...) {
    palette <- match.arg(palette)

    pal <- icb_theme_cols(palette = palette)

    if (reverse) pal <- rev(pal)

    grDevices::colorRampPalette(pal, ...)
}

