#' Calculate Indirectly Standardised ratio for deprivation quintiles, standardised by age and/or sex
#'
#' This function uses negative binomial regression, to counter overdispersion, to adjust data by calculating and expected rate of events, which is compared to the observed event: observed / expected.
#' A ratio of 1 means observed = expected, <1 means observed < expected, and >1 means observed > expected.
#'
#' @param .dt A data.frame contain data you need to calculate the table with the following column names:
#' * numerator - the count of events in question
#' * denominator - the population or group at risk, or group/segment
#' * imd_code - numeric encoded IMD quintile, with unknown coded as 999
#' * age_group_code - age bands used for standardisation.  Bin/age band size is not important provided it is consistent.
#' * sex_group_code - numeric encoded sex
#' @param age TRUE/FALSE whether to include age in the standardisation.
#' @param sex TRUE/FALSE whether to include sex in the standardisation.
#'
#' @returns a data.frame with
#' @export
#'
#' @importFrom stats as.formula coef confint rbinom glm.control
#' @import MASS
#'
#' @examples
#' data(ISR_example)
#' ISR_deprivation(ISR_example)
#'
ISR_deprivation <-
  function(.dt,
           age=TRUE,
           sex=FALSE) {


    # Prepare factors
    .dt$age_group_code_f <- factor(.dt$age_group_code)
    .dt$imd_code_f <- factor(.dt$imd_code, levels = c("1","2","3","4","5","999"),
                             labels = c("1","2","3","4","5","999"))

    # Build formula dynamically using switch
    predictors <- c("imd_code_f")

    if (age) predictors <- c(predictors, "age_group_code_f")
    if (sex) predictors <- c(predictors, "sex_group_code")

    formula_str <- paste("numerator ~", paste(predictors, collapse = " + "), "+ offset(log(denominator))")
    model_formula <- as.formula(formula_str)

    # Fit negative binomial model
    model <- glm.nb(model_formula, data = .dt, control = glm.control(maxit=100))

    cis <- confint(model)

    # Extract coefficients for IMD quintiles
    out_coefs <- data.frame(
      imd_quintile = c("2","3","4","5","999"),
      ratio = exp(coef(model)[2:6]),
      lowerCI = exp(cis[2:6, 1]),
      upperCI = exp(cis[2:6, 2])
    )

    return(out_coefs)
  }



#' Plot function for output parameters of ISR calculation
#'
#' @param .dt A data.frame, generated by ISR_deprivation
#' @param description text to be included in the plot title, default example for MI admissions in 2024/25
#' @param y_scale vector of values, such as the default generated by `seq`.  Default around the 0 - 1.2 range
#'
#' @returns A ggplot object (list)
#' @import ggplot2
#'
#' @export
#'
#' @examples
#' data(ISR_example)
#' standardised_dep <- ISR_deprivation(ISR_example)
#' ISR_deprivation_plot(standardised_dep)
#'
ISR_deprivation_plot <-
  function(.dt,
           description = "Myocardial Infarction (Under 75yrs) - 2024/25",
           y_scale = seq(0,1.5,0.1)) {

    imd_quintile <- ratio <- lowerCI <- upperCI <- NULL

    ggplot(.dt, aes(x = imd_quintile, y = ratio, fill = imd_quintile)) +
      geom_col(show.legend = FALSE, alpha = 0.8) +
      geom_errorbar(aes(ymin = lowerCI, ymax = upperCI, width = 0.5)) +
      geom_hline(yintercept = 1, linetype = "dashed", col = "red", linewidth = 1) +
      scale_fill_brewer(palette = "Dark2") +
      scale_y_continuous(breaks = y_scale) +
      labs(#colour = "Deprivation Quintile",
           x = "IMD Quintile (999 = All (Persons))",
           y = "Indirectly Standardised Ratio",
           title = paste("Age-standardised Admission Ratio Ratios:", description) ,
           subtitle = "A ratio of 1 means the rate = the rate in Quintile 1") +
      theme_minimal() +
      theme(plot.subtitle = element_text(face = "italic")
      )

  }


#' Plot function for output parameters of ISR calculation using Plotly
#'
#' @param .dt A data.frame, generated by ISR_deprivation
#' @param description text to be included in the plot title, default example for MI admissions in 2024/25
#' @return A plotly htmlwidget
#' @import plotly
#'
#' @export
#'
#' @examples
#' data(ISR_example)
#' standardised_dep <- ISR_deprivation(ISR_example)
#' ISR_deprivation_plotly(standardised_dep)
#'
ISR_deprivation_plotly <- function(
    .dt,
    description = "Myocardial Infarction (Under 75 yrs) - 2024/25"
) {

  # Basic checks
  required_cols <- c("imd_quintile", "ratio", "lowerCI", "upperCI")
  missing_cols <- setdiff(required_cols, names(.dt))

  if (length(missing_cols) > 0) {
    stop(
      "Missing required columns: ",
      paste(missing_cols, collapse = ", ")
    )
  }

  # Create error bar columns for plotting
  .dt$upper_error <- .dt$upperCI - .dt$ratio
  .dt$lower_error <- .dt$ratio - .dt$lowerCI

  # Order quintiles
  if (all(.dt$imd_quintile %in% c("1", "2", "3", "4", "5", "999"))) {
    .dt$imd_quintile <- factor(
      .dt$imd_quintile,
      levels = c("1", "2", "3", "4", "5", "999")
    )
  }

  # Custom tooltip
  .dt$tooltip_text <- paste0(
    "IMD Quintile: ", .dt$imd_quintile,
    "<br>Ratio: ", round(.dt$ratio, 2),
    "<br>Lower CI: ", round(.dt$lowerCI, 2),
    "<br>Upper CI: ", round(.dt$upperCI, 2)
  )

  # Bar colours
  bar_cols <- c("#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854", "#ffd92f")

  n_bars <- nrow(.dt)

  plotly::plot_ly(
    data = .dt,
    x = ~imd_quintile,
    y = ~ratio,
    type = "bar",
    text = ~tooltip_text,
    hoverinfo = "text",
    textposition = "none",
    marker = list(
      color = bar_cols[seq_len(n_bars)]
    ),
    error_y = list(
      type = "data",
      symmetric = FALSE,
      array = ~upper_error,
      arrayminus = ~lower_error,
      color = "black"
    )
  ) |>
    plotly::layout(
      title = list(
        text = paste0(
          "Age-standardised Admission Ratio Ratios: ",
          description,
          "<br><i>A ratio of 1 means the rate = the rate in Quintile 1</i>"
        )
      ),
      showlegend = FALSE,
      margin = list(t = 120),
      xaxis = list(title = "IMD Quintile (999 = All Persons)"),
      yaxis = list(title = "Indirectly Standardised Ratio"),
      shapes = list(
        list(
          type = "line",
          x0 = -0.5,
          x1 = n_bars - 0.5,
          y0 = 1,
          y1 = 1,
          line = list(color = "red", width = 2, dash = "dash")
        )
      )
    )
}

#' Prepare ISR deprivation output for reporting
#'
#' This function enriches the output from \code{ISR_deprivation()} by adding
#' interpretation and statistical significance columns.
#' The resulting dataset can be used for reporting tables, for example
#' when creating formatted tables with \code{ISR_deprivation_table()}.
#'
#' The function:
#' - Rounds rate ratios and confidence intervals to two decimal places
#' - Calculates the percentage difference from the reference group (IMD 1)
#' - Generates an interpretation sentence describing the comparison with IMD 1
#' - Determines statistical significance based on whether the confidence interval
#'   crosses 1
#'
#' @param data A data frame produced by \code{ISR_deprivation()} containing the
#'   following columns:
#'   \describe{
#'   \item{imd_quintile}{IMD quintile (2, 3, 4, 5, and 999 representing All Persons).}
#'   \item{ratio}{Rate ratio comparing each IMD quintile against IMD 1 (reference group).}
#'   \item{lowerCI}{Lower bound of the confidence interval for the rate ratio.}
#'   \item{upperCI}{Upper bound of the confidence interval for the rate ratio.}
#'   }
#'
#' @returns A data frame containing the following columns:
#' \describe{
#' \item{IMD Quintile}{Deprivation quintile group.}
#' \item{Ratio}{Rate ratio compared with IMD 1.}
#' \item{Lower CI}{Lower bound of the confidence interval.}
#' \item{Upper CI}{Upper bound of the confidence interval.}
#' \item{Interpretation}{Text interpretation describing the percentage difference
#' from IMD 1 and the associated confidence interval.}
#' \item{Statistical Significance}{Indicates whether the difference compared with
#' IMD 1 is statistically significant.}
#' }
#'
#' @details
#' Statistical significance is determined as follows:
#' \itemize{
#' \item If the lower confidence interval is greater than 1, the rate is considered
#' significantly higher than IMD 1.
#' \item If the upper confidence interval is less than 1, the rate is considered
#' significantly lower than IMD 1.
#' \item Otherwise, the difference is not statistically significant.
#' }
#'
#' @seealso
#' \code{\link{ISR_deprivation}},
#' \code{\link{ISR_deprivation_table}}
#'
#' @examples
#' data(ISR_example)
#'
#' raw_output <- ISR_deprivation(ISR_example)
#'
#' report_table <- make_ISR_deprivation_output(raw_output)
#'
#' @export
#'
#' @importFrom dplyr mutate case_when select
#' @importFrom scales percent
#' @importFrom glue glue
#' @importFrom janitor clean_names
make_ISR_deprivation_output <- function(data) {

  data |>
    dplyr::mutate(
      ratio = round(ratio, 2),
      lowerCI = round(lowerCI, 2),
      upperCI = round(upperCI, 2),
      direction = dplyr::case_when(
        ratio > 1 ~ "↑ Higher",
        ratio < 1 ~ "↓ Lower",
        TRUE ~ "→ Same as"
      ),
      abs_change = scales::percent(abs(ratio - 1), accuracy = 0.1),
      CI_text = paste0(
        scales::percent(lowerCI - 1, accuracy = 0.1), " to ",
        scales::percent(upperCI - 1, accuracy = 0.1)
      ),
      interpretation = dplyr::case_when(
        ratio == 1 ~ "Same as IMD 1 (95% CI: 0.0% to 0.0%)",
        TRUE ~ glue::glue("{abs_change} {direction} than IMD 1 (95% CI: {CI_text})")
      ),
      statistical_significance = dplyr::case_when(
        lowerCI > 1 ~ "Significantly higher than IMD 1",
        upperCI < 1 ~ "Significantly lower than IMD 1",
        TRUE ~ "Not statistically significant"
      )
    ) |>
    dplyr::select(
      imd_quintile,
      ratio,
      lowerCI,
      upperCI,
      interpretation,
      statistical_significance
    ) |>
    janitor::clean_names(case = "title", abbreviations = c("IMD", "CI"))
}

#' Create a formatted gt table for ISR deprivation output
#'
#' This function converts the prepared output from
#' \code{make_ISR_deprivation_output()} into a formatted \code{gt} table
#' for reporting. It applies consistent styling to improve readability and
#' interpretation of deprivation comparisons against IMD 1.
#'
#' The function:
#' - Adds alternating row shading
#' - Centres all columns
#' - Sets a wider width for the Interpretation column
#' - Highlights rate ratios above 1 in red
#' - Highlights rate ratios below 1 in green
#' - Applies background colours to the Statistical Significance column
#' - Bolds all column headers
#'
#' @param data A data frame produced by \code{make_ISR_deprivation_output()}
#'   containing the following columns:
#'   \describe{
#'   \item{IMD Quintile}{Deprivation quintile group.}
#'   \item{Ratio}{Rate ratio compared with IMD 1.}
#'   \item{Lower CI}{Lower bound of the confidence interval.}
#'   \item{Upper CI}{Upper bound of the confidence interval.}
#'   \item{Interpretation}{Narrative interpretation of the comparison with IMD 1.}
#'   \item{Statistical Significance}{Significance category used for cell shading.}
#'   }
#'
#' @returns A \code{gt_tbl} object that can be printed in Quarto, R Markdown,
#' or other reporting workflows.
#'
#' @details
#' The \code{Ratio} column is styled as follows:
#' \itemize{
#' \item Values greater than 1 are shown with red text and a light red background,
#'   indicating a higher rate than IMD 1.
#' \item Values less than 1 are shown with dark green text and a light green
#'   background, indicating a lower rate than IMD 1.
#' \item Values equal to 1 retain the default table styling, indicating no
#'   difference from IMD 1.
#' }
#'
#' The \code{Statistical Significance} column is shaded according to category:
#' \itemize{
#' \item \code{"Significantly higher than IMD 1"} = light red
#' \item \code{"Significantly lower than IMD 1"} = light green
#' \item \code{"Not statistically significant"} = light grey
#' }
#'
#' @seealso
#' \code{\link{ISR_deprivation}},
#' \code{\link{make_ISR_deprivation_output}}
#'
#' @examples
#' data(ISR_example)
#'
#' raw_output <- ISR_deprivation(ISR_example)
#' table_data <- make_ISR_deprivation_output(raw_output)
#'
#' ISR_deprivation_table(table_data)
#'
#' @export
#'
#' @importFrom dplyr mutate case_when
#' @importFrom gt gt opt_row_striping cols_align everything cols_width px
#' @importFrom gt tab_style cell_text cell_fill cells_body
#' @importFrom gt from_column cells_column_labels cols_hide tab_options pct
ISR_deprivation_table <- function(data) {

  sig_colors <- dplyr::case_when(
    data$`Statistical Significance` == "Significantly higher than IMD 1" ~ "#f4cccc",
    data$`Statistical Significance` == "Significantly lower than IMD 1" ~ "#d9ead3",
    TRUE ~ "#f2f2f2"
  )

  data |>
    dplyr::mutate(sig_fill = sig_colors) |>
    gt::gt() |>
    gt::opt_row_striping() |>
    gt::cols_align(
      align = "center",
      columns = gt::everything()
    ) |>
    gt::cols_width(
      Interpretation ~ gt::px(350)
    ) |>
    gt::tab_style(
      style = list(
        gt::cell_text(color = "red"),
        gt::cell_fill(color = "#ffe5e5")
      ),
      locations = gt::cells_body(
        columns = Ratio,
        rows = Ratio > 1
      )
    ) |>
    gt::tab_style(
      style = list(
        gt::cell_text(color = "darkgreen"),
        gt::cell_fill(color = "#e6ffe6")
      ),
      locations = gt::cells_body(
        columns = Ratio,
        rows = Ratio < 1
      )
    ) |>
    gt::tab_style(
      style = gt::cell_fill(color = gt::from_column("sig_fill")),
      locations = gt::cells_body(columns = `Statistical Significance`)
    ) |>
    gt::tab_style(
      style = gt::cell_text(weight = "bold"),
      locations = gt::cells_column_labels(gt::everything())
    ) |>
    gt::cols_hide(columns = sig_fill) |>
    gt::tab_options(
      table.width = gt::pct(100),
      table.align = "center",
      data_row.padding = gt::px(4)
    )
}



#' ISR example dataset
#'
#' An artificial dataset with 6 age bads, 2 sex bands and 5 IMD quintiles plus
#' and unknown coded as 999.
#' This is here to test and demonstrate the function
#' @docType data
#'
#' @keywords datasets
#'
#' @format ## `ISR_example`
#' A data frame with 192 rows and 5 columns:
#' \describe{
#'   \item{age_group_code}{Numerically coded age-bands}
#'   \item{sex_group_code}{Numerically coded sex groups}
#'   \item{imd_code}{Index of multiple deprivation qunitiles, 1-5, 999 = unknown}
#'   \item{numerator}{Numerator of a given indicator}
#'   \item{denominator}{Denominator of a given indicator}
#' }
#'
#' @source Constructed from code <https://github.com/Birmingham-and-Solihull-ICS/BSOLutils/blob/main/data-raw/build_example_data.R>
#'
#' @usage data(ISR_example)
#'
#' @examples
#' data(ISR_example)
#'
"ISR_example"

